name: Build and Push Docker Images
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_tomasz652E: ${{ secrets.DOCKERHUB_tomasz652 }}
      DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    steps:
    # 1. Checkout des Repository-Codes
    - name: Checkout Code
      uses: actions/checkout@v3
    # 2. Login bei Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_tomasz652 }}" --password-stdin
    # 3. Docker-Image für das Frontend erstellen
    - name: Build Frontend Image
      run: |
        docker build -t $DOCKERHUB_tomasz652/frontend:latest ./frontend
    # 4. Docker-Image für das Backend erstellen
    - name: Build Backend Image
      run: |
        docker build -t $DOCKERHUB_tomasz652/backend:latest ./backend
    # 5. Frontend-Image zu Docker Hub pushen
    - name: Push Frontend Image
      run: |
        docker push $DOCKERHUB_tomasz652/frontend:latest
    # 6. Backend-Image zu Docker Hub pushen
    - name: Push Backend Image
      run: |
        docker push $DOCKERHUB_tomasz652/backend:latest





